name: Respaldo Diario Base de Datos

on:
  schedule:
    - cron: '0 3 * * *' # 3:00 AM UTC
  workflow_dispatch:

jobs:
  backup_and_upload:
    runs-on: ubuntu-latest
    name: Crear Dump y Subir a Drive
    
    steps:
      - name: Instalar Cliente PostgreSQL 18
        run: |
          # 1. Instalar herramientas del repositorio
          sudo apt-get install -y postgresql-common
          # 2. Aceptar configuración automática del repo oficial
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          # 3. Actualizar e instalar la versión 18
          sudo apt-get update
          sudo apt-get install -y postgresql-client-18

      - name: Crear Respaldo SQL
        env:
          PG_DB_URL: ${{ secrets.DATABASE_URL }}
        run: |
          FILE_NAME="backup_$(date +%Y-%m-%d_%H-%M).sql"
          echo "FILE_NAME=$FILE_NAME" >> $GITHUB_ENV
          
          # --- AQUÍ ESTÁ EL CAMBIO CLAVE ---
          # Usamos la ruta absoluta de la versión 18 para evitar errores
          /usr/lib/postgresql/18/bin/pg_dump "$PG_DB_URL" > "$FILE_NAME"
          
          echo "✅ Respaldo creado: $FILE_NAME"

      - name: Instalar y Configurar Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONF }}

      - name: Subir a Google Drive
        run: |
          # 'gdrive' es el nombre que pusiste en el config
          # 'Backups_BaseDatos' es tu carpeta en Drive
          rclone copy "$FILE_NAME" "gdrive:Backups_BaseDatos"
          echo "🚀 Subida completada con éxito"